# Generated by Django 5.0.14 on 2026-09-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('facultad', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField()),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online'), ('Híbrida', 'Híbrida')], max_length=20)),
                ('jornada', models.CharField(choices=[('Diurna', 'Diurna'), ('Vespertina', 'Vespertina')], max_length=20)),
                ('arancel', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cupos', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
